/**
 * MyFitnessApp
 * A REST api for exercise and workout tracking
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrupoMuscular } from './grupoMuscular';


export interface Ejercicio { 
    id?: number;
    nombre?: string;
    grupoMuscularPrimario?: GrupoMuscular;
    grupoMuscularSecundario?: GrupoMuscular;
    tipoDeEjercicio?: Ejercicio.TipoDeEjercicioEnum;
}
export namespace Ejercicio {
    export type TipoDeEjercicioEnum = 'PESO_Y_REPETICIONES' | 'PESO_CORPORAL' | 'PESO_CORPORAL_CON_PESO_EXTRA' | 'PESO_CORPORAL_ASISTIDO' | 'DISTANCIA_Y_DURACION' | 'DISTANCIA_Y_PESO' | 'DURACION';
    export const TipoDeEjercicioEnum = {
        PesoYRepeticiones: 'PESO_Y_REPETICIONES' as TipoDeEjercicioEnum,
        PesoCorporal: 'PESO_CORPORAL' as TipoDeEjercicioEnum,
        PesoCorporalConPesoExtra: 'PESO_CORPORAL_CON_PESO_EXTRA' as TipoDeEjercicioEnum,
        PesoCorporalAsistido: 'PESO_CORPORAL_ASISTIDO' as TipoDeEjercicioEnum,
        DistanciaYDuracion: 'DISTANCIA_Y_DURACION' as TipoDeEjercicioEnum,
        DistanciaYPeso: 'DISTANCIA_Y_PESO' as TipoDeEjercicioEnum,
        Duracion: 'DURACION' as TipoDeEjercicioEnum
    };
}


