/**
 * MyFitnessApp
 * A REST api for exercise and workout tracking
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemRutinaRes } from './itemRutinaRes';


export interface EntrenoRes { 
    id?: number;
    titulo?: string;
    fecha?: string;
    duracionEnSeg?: number;
    volumenEnKg?: number;
    nroDeSeries?: number;
    items?: Array<ItemRutinaRes>;
}

