/**
 * MyFitnessApp
 * A REST api for exercise and workout tracking
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemRutinaRequestDto } from './itemRutinaRequestDto';


export interface EntrenoRequestDto { 
    rutinaId: number;
    inicio: string;
    duracionEnMinutos: number;
    items: Array<ItemRutinaRequestDto>;
}

