/**
 * MyFitnessApp
 * A REST api for exercise and workout tracking
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SerieRes } from './serieRes';
import { EjercicioRes } from './ejercicioRes';


export interface ItemRutinaRes {
    id?: number;
    ejercicio?: EjercicioRes;
    descansoEnSeg?: number;
    nota?: string;
    series?: Array<SerieRes>;
}

