/**
 * MyFitnessApp
 * A REST api for exercise and workout tracking
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SerieRequestDto } from './serieRequestDto';


export interface ItemRutinaRequestDto { 
    ejercicioId: number;
    descansoEnSeg: number;
    nota: string;
    series: Array<SerieRequestDto>;
}

