export * from './ejercicioReq';
export * from './ejercicioRes';
export * from './entrenoReq';
export * from './itemRutinaReq';
export * from './itemRutinaRes';
export * from './rutinaReq';
export * from './rutinaRes';
export * from './serieReq';
export * from './serieRes';
