spring:
  application:
    name: myfitnessapp
  datasource:
    url: ${DATABASE:jdbc:mysql://localhost:3306/myfitnessapp?createDatabaseIfNotExist=true} #La bd se crea automaticamente si no existe
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

springdoc:
  default-produces-media-type: application/json

frontend:
  baseUrl: ${FRONT_BASE_URL:http://localhost:4200}